import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thian Hooi&apos;s Learning Loop Submission</title>
        <meta name="description" content="Generated by next js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Thian Hooi&apos;s Learning Loop Submission</h1>
    </div>
  );
}
